apiVersion: v1
kind: Service
metadata:
  # hardcoded name due to eureka stack
  name: registry
  labels:
{{ include "registry.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  clusterIP: None # use for HA
  selector:
    app.kubernetes.io/name: {{ include "registry.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
