management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  rabbitmq:
    host: rabbitmq-ha
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      discovery:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://keycloak-dev.1e242a63d7484862a97a.westeurope.aksapp.io/auth/realms/EntsoeAATRealm/protocol/openid-connect/certs
  #          jwk-set-uri: http://oauth2:8080/auth/jwks.json
  data:
    mongodb:
      uris:
        - mongodb://root:password@mongodb:27017/operator-fabric?authSource=admin&authMode=scram-sha1
eureka:
  client:
    service-url:
      #ENABLE FOR HA 
      defaultZone: http://registry-0.registry:8080/eureka/,http://registry-1.registry:8080/eureka/
      #defaultZone: http://registry-0.registry:8080/eureka/
    region: default
  registryFetchIntervalSeconds: 5

operatorfabric:
  security:
    oauth2:
      client-id: LetsCo
      client-secret: 71cc8849-c47a-40a6-bff7-626cda41dbde
    jwt:
      login-claim: preferred_username
      expire-claim: exp